# 服务环境全局配置
profile-env: ${profile-env}

my:
  name: liuailan-test
  age: 28

test:
  name: liuailan-test
  age: 28
  sex: girl
  local: shanxi

spring:
  datasource:
    configs:
      master:
        jdbc-url: jdbc:mysql://127.0.0.1/zhenrongbao?useUnicode=true&characterEncoding=utf8
        username: root
        password: root
        # hikari:
        minimum-idle: 1
        maximum-pool-size: 5

      slave:
        jdbc-url: jdbc:mysql://127.0.0.1/zhenrongbao?useUnicode=true&characterEncoding=utf8
        username: root
        password: root
        # hikari:
        minimum-idle: 1
        maximum-pool-size: 5
