# 服务环境全局配置
profile-env: ${profile-env}

my:
  name: liuailan-dev
  age: 28

test:
  name: liuailan-dev
  age: 28
  sex: girl
  local: shanxi

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/zhenrongbao
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update  # 第一次简表create  后面用update
    show-sql: true